[package]
name = "rainbow_table"
version = "0.1.0"
edition = "2021"

[lib]
name = "rainbow_table"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.3", features = ["extension-module"] }
sha1 = "0.10.5"